source=~/.config/hypr/hyprlock/colors.conf

# FONDO
background {
    monitor =
    path = $HOME/.config/hypr/lock_bg.jpg
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 0 
    contrast = 0.8916
    brightness = 0.8172
}

# RELOJ ESTILO "END OF WANDERING" (GRANDE Y FINO)
label { # Clock
    monitor =
    # Formato de 24h con dos puntos elegantes
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 0.6) # Blanco con transparencia como en la foto
    font_size = 180 # Tamaño masivo para que destaque
    font_family = JetBrains Mono ExtraLight # Usamos la variante más fina

    position = 0, 180 
    halign = center
    valign = center
}

# FECHA MINIMALISTA
label { # Date
    monitor =
    text = cmd[update:5000] date +"%A, %d %B"
    color = rgba(255, 255, 255, 0.5)
    font_size = 24
    font_family = JetBrains Mono Light

    position = 0, 80 
    halign = center
    valign = center
}

# CAMPO DE CONTRASEÑA
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.2
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(0, 0, 0, 0.3)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    placeholder_text = <i>Contraseña...</i>

    position = 0, -140 
    halign = center
    valign = center
}

# ELIMINAMOS O BAJAMOS EL RESTO PARA QUE NO ESTORBE LA VISTA
label { # User
    monitor =
    text =   $USER
    color = rgba(255, 255, 255, 0.4)
    font_size = 16
    font_family = $font_family
    position = 0, 40
    halign = center
    valign = bottom
}

# Mantenemos las advertencias de sistema discretas
label { # Caps Lock Warning
    monitor =
    text = cmd[update:250] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprlock/check-capslock.sh
    color = $text_color
    font_size = 12
    position = 0, -80
    halign = center
    valign = center
}
