# --- MONITORES ---
monitor=eDP-1, 1366x768@60, 0x0, 1
monitor=HDMI-A-1, 1920x1080@60, 1366x0, 1

# --- CONFIGURACIÓN GENERAL ---
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3
    col.active_border = rgba(0DB7D4FF) rgba(0077FFFF) 45deg
    col.inactive_border = rgba(31313688)
}

# --- DECORACIÓN (Optimizado para Gaming) ---
decoration {
    rounding = 12

    # Casi opaco para jugar mejor (0.95)
    active_opacity = 0.95
    inactive_opacity = 0.85

    blur {
        enabled = true
        size = 10
        passes = 4
        new_optimizations = true
        ignore_opacity = true
    }

    shadow {
        enabled = true
        range = 15
        color = rgba(00000066)
    }

    dim_inactive = true
    dim_strength = 0.1
}

# --- ANIMACIONES ---
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 5, myBezier
    animation = workspaces, 1, 6, default
}

# --- MISCELÁNEO (Rendimiento para Ryzen Vega 8) ---
misc {
    vfr = true
    vrr = 1
    disable_hyprland_logo = true
}
# --- ENTRADA (Teclado y Ratón) ---
input {
    # Configuración de idiomas: Español y Americano
    kb_layout = es, us
    
    # Opción para cambiar entre ellos con Alt + Shift
    kb_options = grp:alt_shift_toggle
    
    follow_mouse = 1
    sensitivity = 0 # Sin aceleración para mejor puntería en juegos
}
